// Kickers Country Bar — Wix Events widget on a Wix-hosted site.
// Events are rendered server-side into the HTML, so cheerio is enough.
// Source: https://www.kickersjax.com/upcoming-events
//
// Wix's autogenerated class names (e.g. .MTyds5) are unstable across deploys,
// so we target the stable data-hook attributes instead. Title comes from the
// image alt because the title text node itself has no data-hook.

import * as cheerio from "cheerio";
import type { EventInput } from "@/lib/db";
import type { Category } from "@/lib/categories";

const URL = "https://www.kickersjax.com/upcoming-events";

const VENUE_NAME = "Kickers Country Bar";
const VENUE_ADDRESS = "14333 Beach Blvd, Jacksonville Beach, FL 32250";
const VENUE_CITY = "Jacksonville Beach";

export async function fetchKickers(): Promise<EventInput[]> {
  const res = await fetch(URL, {
    headers: { "user-agent": "Mozilla/5.0 (jax-events local scraper)" },
  });
  if (!res.ok) throw new Error(`Kickers HTTP ${res.status}`);
  const html = await res.text();
  const $ = cheerio.load(html);

  const out: EventInput[] = [];
  $('li[data-hook="events-card"]').each((_, el) => {
    const $el = $(el);
    // Title isn't in a data-hook node. The image alt usually carries it, but
    // cheerio in different runtimes (Next bundling vs raw Node) handles the
    // surrounding <wow-image> custom element inconsistently — sometimes it
    // returns "" for img[data-hook=image]. Take any descendant <img alt=...>
    // first, and fall back to scanning the card text with the date string
    // removed.
    const altFromImg =
      $el
        .find("img")
        .filter((_, n) => !!$(n).attr("alt"))
        .first()
        .attr("alt") ?? "";
    const dateStr = $el.find('[data-hook="date"]').first().text().trim();
    let rawTitle = altFromImg.trim();
    if (!rawTitle) {
      const fullText = $el.text().trim().replace(/\s+/g, " ");
      rawTitle = dateStr ? fullText.replace(dateStr, "").trim() : fullText;
    }
    if (!rawTitle || !dateStr) return;

    const { title, free } = stripFreeMarker(rawTitle);
    const { starts, ends } = parseKickersDate(dateStr);
    if (!starts) return;

    out.push({
      source: "kickers",
      source_id: `${starts.toISOString().slice(0, 10)}-${slugify(title)}`,
      title,
      url: URL,
      starts_at: starts.toISOString(),
      ends_at: ends ? ends.toISOString() : null,
      venue_name: VENUE_NAME,
      venue_address: VENUE_ADDRESS,
      city: VENUE_CITY,
      price_min: free ? 0 : null,
      categories: classify(title),
    });
  });

  return out;
}

// Kickers convention: "AC Scar - FREE" / "Cam Wheaton - FREE". The " - FREE"
// suffix is a price marker, not part of the artist name — strip it for the
// stored title but remember the signal.
function stripFreeMarker(raw: string): { title: string; free: boolean } {
  const m = raw.match(/^(.+?)\s*[-–—]\s*FREE\s*$/i);
  if (m) return { title: m[1].trim(), free: true };
  return { title: raw.trim(), free: false };
}

// Date strings come in two shapes:
//   "May 22, 2026, 9:00 PM"
//   "May 30, 2026, 9:00 PM – May 31, 2026, 1:00 AM"
function parseKickersDate(s: string): { starts: Date | null; ends: Date | null } {
  // Wix uses en-dash (–), em-dash (—), or hyphen for ranges.
  const parts = s.split(/\s+[–—\-]\s+/);
  const starts = parseOne(parts[0]);
  const ends = parts[1] ? parseOne(parts[1]) : null;
  return { starts, ends };
}

function parseOne(s: string): Date | null {
  // Expect "May 22, 2026, 9:00 PM" — let the Date constructor handle it. We
  // also accept the spaced variant with no Oxford comma just in case.
  const m = s.match(
    /([A-Za-z]+)\s+(\d{1,2}),?\s+(\d{4}),?\s+(\d{1,2}):(\d{2})\s*(AM|PM)/i
  );
  if (!m) return null;
  const months: Record<string, number> = {
    Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5,
    Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11,
  };
  const month = months[m[1].slice(0, 3)];
  if (month === undefined) return null;
  const day = parseInt(m[2], 10);
  const year = parseInt(m[3], 10);
  let hour = parseInt(m[4], 10);
  const minute = parseInt(m[5], 10);
  if (/pm/i.test(m[6]) && hour < 12) hour += 12;
  if (/am/i.test(m[6]) && hour === 12) hour = 0;
  return new Date(year, month, day, hour, minute, 0);
}

function classify(title: string): Category[] {
  const t = title.toLowerCase();
  const cats = new Set<Category>();

  if (/line dance|line dancing/.test(t)) {
    cats.add("dance-other");
    if (/lesson|class/.test(t)) cats.add("learning-workshop");
  }
  // Everything else at Kickers is a live country act.
  if (cats.size === 0) cats.add("music-live-other");
  return Array.from(cats);
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
