// One-off importer for the weekly "Community Events in Jacksonville, FL" digest.
//
// These are the small free/civic events (JaxParks fitness classes, neighborhood
// markets, run clubs, community meetings) that none of the automated scrapers
// reach — visit-jax and dtjax only carry a fraction of them, and the JaxParks
// class schedule lives behind a registration portal with no feed.
//
// Idempotent: every entry has a stable source_id, so re-running updates in place
// rather than duplicating. Events already covered accurately by an existing
// source (Ron White, Sporting Jax, Jaguars) are deliberately omitted — see the
// SKIPPED list at the bottom for why.
//
// Usage:  npx tsx scripts/add-community-digest.ts

import { getDb, upsertEvent, type EventInput } from "../src/lib/db";

// Everything below is Jacksonville in September = EDT (UTC-4).
const TZ = "-04:00";
const at = (day: string, time: string) => `2026-09-${day}T${time}:00${TZ}`;

const JAXPARKS = "https://jaxparks.coj.net/";
const DTJAX = "https://dtjax.com/events/";

const EVENTS: EventInput[] = [
  // ---------- Monday, September 7 (Labor Day) ----------
  {
    source: "community-digest",
    source_id: "2026-09-07-step-aerobics-ram",
    title: "Step Aerobics at Riverside Arts Market",
    description: "Free outdoor step aerobics under the Fuller Warren Bridge. Pre-registration required via the JaxParks portal.",
    url: JAXPARKS,
    starts_at: at("07", "18:30"),
    ends_at: at("07", "19:30"),
    venue_name: "Riverside Arts Market",
    venue_address: "715 Riverside Ave",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness"],
  },

  // ---------- Tuesday, September 8 ----------
  {
    source: "community-digest",
    source_id: "2026-09-08-senior-fit-chair-yoga",
    title: "Senior Fit: Chair Yoga",
    description: "Free chair yoga for seniors at Memorial Park. Part of the JaxParks Senior Fit series.",
    url: JAXPARKS,
    starts_at: at("08", "10:00"),
    ends_at: at("08", "11:00"),
    venue_name: "Memorial Park",
    venue_address: "1620 Riverside Ave",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["yoga", "health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-08-jumbo-shrimp-doubleheader",
    title: "Jumbo Shrimp vs. Gwinnett Stripers (Doubleheader)",
    description: "Opener of the final 2026 homestand. Game one at 5:05pm, game two 30 minutes after game one ends. Boat Hat giveaway.",
    url: "https://www.milb.com/jacksonville/schedule",
    starts_at: at("08", "17:05"),
    venue_name: "VyStar Ballpark",
    venue_address: "301 A Philip Randolph Blvd",
    city: "Jacksonville",
    categories: ["sports"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-08-zumba-friendship-fountain",
    title: "Free Zumba at Friendship Fountain",
    description: "Free outdoor Zumba class on the Southbank Riverwalk.",
    url: "https://dtjax.com/events/zumba-at-gefen/2026-09-08/",
    starts_at: at("08", "18:00"),
    ends_at: at("08", "19:00"),
    venue_name: "Friendship Fountain",
    venue_address: "1015 Museum Cir",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["dance-other", "health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-08-yoga-ram",
    title: "Yoga at Riverside Arts Market",
    description: "Free evening yoga class under the Fuller Warren Bridge.",
    url: JAXPARKS,
    starts_at: at("08", "18:00"),
    ends_at: at("08", "19:00"),
    venue_name: "Riverside Arts Market",
    venue_address: "715 Riverside Ave",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["yoga", "health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-08-jax-run-club",
    title: "Jacksonville Run Club",
    description: "Free group run starting at Friendship Fountain. All paces welcome.",
    url: "https://www.instagram.com/jacksonvillerunclub/",
    starts_at: at("08", "18:00"),
    venue_name: "Friendship Fountain",
    venue_address: "1015 Museum Cir",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness", "sports"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-08-total-body-strength-corkscrew",
    title: "Total Body Strength at Corkscrew Park",
    description: "Free total-body strength class. Register through the JaxParks portal.",
    url: JAXPARKS,
    starts_at: at("08", "18:00"),
    ends_at: at("08", "19:00"),
    venue_name: "Corkscrew Park",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-08-conditioning-emmett-reed",
    title: "Conditioning Fitness Class at Emmett Reed Center",
    description: "Free conditioning class at the Emmett Reed Community Center.",
    url: JAXPARKS,
    starts_at: at("08", "18:00"),
    ends_at: at("08", "19:00"),
    venue_name: "Emmett Reed Center",
    venue_address: "1093 W 6th St",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-08-seabreeze-square-dance",
    title: "Seabreeze Square Dance Club",
    description: "Weekly Tuesday square dance. Free and welcoming to newcomers.",
    url: "https://www.dancergram.com/aa-FWS/clubpages/seabreezesingles/",
    starts_at: at("08", "19:00"),
    venue_name: "Frances Padgett Arlington Senior Center",
    venue_address: "1078 Rogero Rd",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["dance-other"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-08-poi-flow-arts-ram",
    title: "Poi & Flow Arts Performance Workshop",
    description: "Free flow-arts / poi spinning workshop at Riverside Arts Market.",
    url: DTJAX,
    starts_at: at("08", "19:30"),
    venue_name: "Riverside Arts Market",
    venue_address: "715 Riverside Ave",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["learning-workshop", "experiential"],
  },

  // ---------- Wednesday, September 9 ----------
  {
    source: "community-digest",
    source_id: "2026-09-09-emerald-trail-meeting",
    title: "Emerald Trail Community Meeting",
    description: "First look at the proposed 60% design of the Emerald Trail City Center Link, from Bay Street to Hogans Creek. Free and open to the public.",
    url: "https://dtjax.com/events/emerald-trail-community-meeting/",
    starts_at: at("09", "17:30"),
    ends_at: at("09", "19:00"),
    venue_name: "Downtown Vision Office",
    venue_address: "29 W Duval St",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["intellectual-discussion"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-09-yoga-riversedge",
    title: "Yoga at RiversEdge Lawn",
    description: "Free outdoor yoga on the RiversEdge lawn.",
    url: JAXPARKS,
    starts_at: at("09", "18:00"),
    ends_at: at("09", "19:00"),
    venue_name: "RiversEdge Lawn",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["yoga", "health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-09-hip-hop-dance-levs",
    title: "Hip Hop Dance Class at LEVS Park",
    description: "Free hip hop dance class at Lift Ev'ry Voice and Sing Park.",
    url: DTJAX,
    starts_at: at("09", "18:00"),
    ends_at: at("09", "19:00"),
    venue_name: "Lift Ev'ry Voice and Sing Park",
    venue_address: "120 Lee St",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["dance-other", "music-00s-hiphop"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-09-family-movie-night-block",
    title: "Family Movie Night: Monsters University",
    description: "Free outdoor family movie screening at The Block Jax.",
    url: "https://www.theblockjax.com/",
    starts_at: at("09", "18:00"),
    venue_name: "The Block Jax",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["kids-family"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-09-904-walk-club",
    title: "904 Walk Club Meet and Greet",
    description: "Meet and greet at 6:30pm, walk steps off at 7pm. Location announced on their social — follow before heading out.",
    url: "https://www.instagram.com/904walkclub/",
    starts_at: at("09", "18:30"),
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-09-mat-pilates-630",
    title: "Mat Pilates at Riverfront Music Garden (6:30pm)",
    description: "Free 30-minute mat Pilates class led by JETSET Pilates. Bring your own mat.",
    url: "https://dtjax.com/organizer/jetset-pilates/",
    starts_at: at("09", "18:30"),
    ends_at: at("09", "19:00"),
    venue_name: "Riverfront Music Garden",
    venue_address: "300 Water St",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-09-mat-pilates-715",
    title: "Mat Pilates at Riverfront Music Garden (7:15pm)",
    description: "Second free 30-minute mat Pilates session of the evening. Bring your own mat.",
    url: "https://dtjax.com/organizer/jetset-pilates/",
    starts_at: at("09", "19:15"),
    ends_at: at("09", "19:45"),
    venue_name: "Riverfront Music Garden",
    venue_address: "300 Water St",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-09-jumbo-shrimp",
    title: "Jumbo Shrimp vs. Gwinnett Stripers",
    description: "Game 3 of the final 2026 homestand.",
    url: "https://www.milb.com/jacksonville/schedule",
    starts_at: at("09", "19:05"),
    venue_name: "VyStar Ballpark",
    venue_address: "301 A Philip Randolph Blvd",
    city: "Jacksonville",
    categories: ["sports"],
  },

  // ---------- Thursday, September 10 ----------
  {
    source: "community-digest",
    source_id: "2026-09-10-hiit-ram",
    title: "HIIT Class at Riverside Arts Market",
    description: "Free high-intensity interval training class under the Fuller Warren Bridge.",
    url: JAXPARKS,
    starts_at: at("10", "18:00"),
    ends_at: at("10", "19:00"),
    venue_name: "Riverside Arts Market",
    venue_address: "715 Riverside Ave",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-10-yoga-levs",
    title: "Ev'rybody Yoga at LEVS Park",
    description: "Free yoga session for \"every age, capacity, and culture\" at Lift Ev'ry Voice and Sing Park.",
    url: "https://dtjax.com/events/evrybody-yoga-at-levs-park/2026-09-10/",
    starts_at: at("10", "18:00"),
    ends_at: at("10", "19:30"),
    venue_name: "Lift Ev'ry Voice and Sing Park",
    venue_address: "120 Lee St",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["yoga", "health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-10-high-impact-emmett-reed",
    title: "High-Impact Fitness Class at Emmett Reed Center",
    description: "Free high-impact fitness class at the Emmett Reed Community Center.",
    url: JAXPARKS,
    starts_at: at("10", "18:00"),
    ends_at: at("10", "19:00"),
    venue_name: "Emmett Reed Center",
    venue_address: "1093 W 6th St",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-10-united-way-yp-mixer",
    title: "Cocktails and Conversation: United Way Young Professionals Mixer",
    description: "Networking mixer hosted by Atlantic Circle, United Way of Northeast Florida's rising-professionals group. Small-group discussions with Northeast Florida philanthropists.",
    url: "https://unitedwaynefl.org/event/atlantic-circle-cocktails-and-conversations/",
    starts_at: at("10", "18:00"),
    venue_name: "Community First Igloo",
    venue_address: "300 A Philip Randolph Blvd",
    city: "Jacksonville",
    categories: ["food-drink", "intellectual-discussion"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-10-yoga-hazouri",
    title: "Yoga at Tommy Hazouri Sr. Park",
    description: "Free evening yoga class in Mandarin.",
    url: JAXPARKS,
    starts_at: at("10", "18:15"),
    ends_at: at("10", "19:15"),
    venue_name: "Tommy Hazouri Sr. Park",
    venue_address: "14780 Mandarin Rd",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["yoga", "health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-10-sombrero-running",
    title: "Walk/Run with Sombrero Running",
    description: "Free weekly group walk/run leaving from Riverside Arts Market.",
    url: "https://www.instagram.com/sombrerorunning/",
    starts_at: at("10", "18:30"),
    venue_name: "Riverside Arts Market",
    venue_address: "715 Riverside Ave",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness", "sports"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-10-fishweir-fun-run",
    title: "Community Fun Run at Fishweir Brewing",
    description: "Free weekly fun run out of Fishweir Brewing Company, beer afterward.",
    url: "https://www.fishweirbrewing.com/",
    starts_at: at("10", "19:00"),
    venue_name: "Fishweir Brewing Company",
    venue_address: "1183 Edgewood Ave S",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness", "food-drink"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-10-jumbo-shrimp",
    title: "Jumbo Shrimp vs. Gwinnett Stripers",
    description: "Game 4 of the final 2026 homestand.",
    url: "https://www.milb.com/jacksonville/schedule",
    starts_at: at("10", "19:05"),
    venue_name: "VyStar Ballpark",
    venue_address: "301 A Philip Randolph Blvd",
    city: "Jacksonville",
    categories: ["sports"],
  },

  // ---------- Friday, September 11 ----------
  {
    source: "community-digest",
    source_id: "2026-09-11-asian-night-market",
    title: "Asian Night Market (Friday)",
    description: "Free entry. 15+ local vendors serving Filipino, Thai, Korean, Cambodian and Vietnamese street food, plus karaoke and dance performances.",
    url: "https://www.visitjacksonville.com/events/asian-night-market-jacksonville-southside/",
    starts_at: at("11", "16:00"),
    ends_at: at("11", "22:00"),
    venue_name: "RD International Market",
    venue_address: "7534 Beach Blvd",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["festival", "food-drink", "market-shopping"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-11-jumbo-shrimp",
    title: "Jumbo Shrimp vs. Gwinnett Stripers (Fireworks)",
    description: "Miller Lites Happy Hour with post-game fireworks.",
    url: "https://www.milb.com/jacksonville/schedule",
    starts_at: at("11", "19:05"),
    venue_name: "VyStar Ballpark",
    venue_address: "301 A Philip Randolph Blvd",
    city: "Jacksonville",
    categories: ["sports"],
  },

  // ---------- Saturday, September 12 ----------
  {
    source: "community-digest",
    source_id: "2026-09-12-jax-run-club",
    title: "Jacksonville Run Club (Saturday)",
    description: "Free Saturday morning group run from Friendship Fountain.",
    url: "https://www.instagram.com/jacksonvillerunclub/",
    starts_at: at("12", "07:00"),
    venue_name: "Friendship Fountain",
    venue_address: "1015 Museum Cir",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness", "sports"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-halsema-parkrun",
    title: "Halsema Trailhead parkrun (free timed 5K)",
    description: "Free weekly timed 5K on the Jacksonville-Baldwin Rail Trail. Register once online and bring your barcode.",
    url: "https://www.parkrun.us/halsematrailhead/",
    starts_at: at("12", "07:30"),
    venue_name: "Jacksonville-Baldwin Rail Trail — Halsema Road Trailhead",
    venue_address: "1383 Halsema Rd N",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness", "outdoor-nature", "sports"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-ed-austin-parkrun",
    title: "Ed Austin parkrun (free timed 5K)",
    description: "Free weekly timed 5K at Ed Austin Regional Park. Register once online and bring your barcode.",
    url: "https://www.parkrun.us/",
    starts_at: at("12", "07:30"),
    venue_name: "Ed Austin Regional Park",
    venue_address: "11751 McCormick Rd",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness", "outdoor-nature", "sports"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-bootcamp-emmett-reed",
    title: "Bootcamp Fitness Class at Emmett Reed Center",
    description: "Free Saturday morning bootcamp class.",
    url: JAXPARKS,
    starts_at: at("12", "09:00"),
    ends_at: at("12", "10:00"),
    venue_name: "Emmett Reed Center",
    venue_address: "1093 W 6th St",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-brooklyn-clean-up",
    title: "Brooklyn Community Clean Up",
    description: "Neighborhood clean-up meeting at Sidney J. Gefen Riverwalk Park.",
    url: "https://dtjax.com/events/brooklyn-community-clean-up/",
    starts_at: at("12", "09:00"),
    ends_at: at("12", "11:00"),
    venue_name: "Sidney J. Gefen Riverwalk Park",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["outdoor-nature", "experiential"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-yoga-ram",
    title: "Yoga at Riverside Arts Market",
    description: "Free 9am yoga every Saturday before the market opens.",
    url: JAXPARKS,
    starts_at: at("12", "09:00"),
    ends_at: at("12", "10:00"),
    venue_name: "Riverside Arts Market",
    venue_address: "715 Riverside Ave",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["yoga", "health-wellness"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-castaway-nature-walk",
    title: "Free Nature Walk at Castaway Island Preserve",
    description: "Park naturalists lead a leisurely ~1 mile walk on the Island trail, pointing out plants and animals. ADA accessible and stroller-friendly.",
    url: "https://www.jacksonville.gov/departments/parks-and-recreation/jaxparks/environmental-education",
    starts_at: at("12", "09:00"),
    venue_name: "Castaway Island Preserve",
    venue_address: "2921 San Pablo Rd S",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["outdoor-nature", "learning-workshop"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-riverside-arts-market",
    title: "Riverside Arts Market",
    description: "Nearly 150 makers every Saturday under the Fuller Warren Bridge.",
    url: "https://dtjax.com/events/riverside-arts-market-pi-day/2026-09-12/",
    starts_at: at("12", "10:00"),
    ends_at: at("12", "15:00"),
    venue_name: "Riverside Arts Market",
    venue_address: "715 Riverside Ave",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["market-shopping", "festival"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-art-in-the-park",
    title: "Art in the Park: Watercolor Painting",
    description: "Free outdoor watercolor painting session. Register in advance.",
    url: JAXPARKS,
    starts_at: at("12", "10:00"),
    venue_name: "RiversEdge Park",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["art-class", "experiential"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-earthas-farm-market",
    title: "Eartha's Farm & Market",
    description: "Weekly Saturday farmers market on Moncrief Road. (Their own site lists an 8:30am open — the digest says 10am.)",
    url: "https://earthasfarmandmarket.org/",
    starts_at: at("12", "10:00"),
    ends_at: at("12", "14:00"),
    venue_name: "Eartha's Farm & Market",
    venue_address: "4850 Moncrief Rd",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["market-shopping", "food-drink"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-moca-free-saturday",
    title: "Free Saturdays at MOCA",
    description: "VyStar-sponsored free admission to the Museum of Contemporary Art every Saturday, 11am-5pm. No registration required.",
    url: "https://dtjax.com/events/free-saturdays-at-moca/2026-09-12/",
    starts_at: at("12", "11:00"),
    ends_at: at("12", "17:00"),
    venue_name: "MOCA Jacksonville",
    venue_address: "333 N Laura St",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["art-exhibition"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-ritz-community-appreciation",
    title: "Ritz Theatre & Museum Community Appreciation Day",
    description: "Free admission, celebrating 27 years since the Ritz reopened. NOTE: date is from the community digest and was not independently confirmed on the Ritz site — verify before going.",
    url: "https://www.ritzjacksonville.com/",
    starts_at: at("12", "11:00"),
    ends_at: at("12", "17:00"),
    venue_name: "Ritz Theatre & Museum",
    venue_address: "829 N Davis St",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["art-exhibition", "festival"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-central-bark-puppy-hour",
    title: "Puppy Hour at Central Bark",
    description: "Free supervised puppy playtime and social hour for pups 8-24 weeks (or under 30 lbs). Must register in advance to secure a spot.",
    url: "https://www.centralbarkusa.com/jacksonville/puppy-hour/",
    starts_at: at("12", "12:00"),
    ends_at: at("12", "13:00"),
    venue_name: "Central Bark Jacksonville",
    venue_address: "5614 San Jose Blvd",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["experiential"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-asian-night-market",
    title: "Asian Night Market (Saturday)",
    description: "Second night of the bi-monthly market. Free entry, 15+ vendors, karaoke and dance performances.",
    url: "https://www.visitjacksonville.com/events/asian-night-market-jacksonville-southside/",
    starts_at: at("12", "16:00"),
    ends_at: at("12", "22:00"),
    venue_name: "RD International Market",
    venue_address: "7534 Beach Blvd",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["festival", "food-drink", "market-shopping"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-lavilla-marketplace",
    title: "LaVilla Marketplace",
    description: "Evening market at Lift Ev'ry Voice and Sing Park in LaVilla.",
    url: DTJAX,
    starts_at: at("12", "17:00"),
    ends_at: at("12", "20:00"),
    venue_name: "Lift Ev'ry Voice and Sing Park",
    venue_address: "120 Lee St",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["market-shopping", "food-drink"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-live-jazz-riversedge",
    title: "Live Jazz at RiversEdge Park",
    description: "Free live jazz on the RiversEdge lawn.",
    url: DTJAX,
    starts_at: at("12", "18:00"),
    venue_name: "RiversEdge Park",
    city: "Jacksonville",
    price_min: 0,
    price_max: 0,
    categories: ["music-swing-jazz", "music-live-other"],
  },
  {
    source: "community-digest",
    source_id: "2026-09-12-jumbo-shrimp-final",
    title: "Jumbo Shrimp — Final Home Game of 2026",
    description: "Last home game of the season, closing out the Gwinnett Stripers series.",
    url: "https://www.milb.com/jacksonville/schedule",
    starts_at: at("12", "18:35"),
    venue_name: "VyStar Ballpark",
    venue_address: "301 A Philip Randolph Blvd",
    city: "Jacksonville",
    categories: ["sports"],
  },
];

// Already present and accurate from an existing scraper — deliberately not re-added:
//   Ron White, Sep 11 8pm Moran Theater  -> visit-jax + florida-theatre
//   Sporting Jax vs Rhode Island FC, Sep 12 7pm Hodges -> visit-jax
//   Jaguars vs Browns (home opener), Sep 13 1pm -> visit-jax

function main() {
  const db = getDb();
  const tx = db.transaction(() => {
    for (const e of EVENTS) upsertEvent(db, e);
  });
  tx();
  console.log(`upserted ${EVENTS.length} community-digest events`);
}

main();
